# Generated by Django 4.2 on 2023-06-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rohan', '0002_alter_contactus_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='contactus',
            name='phone',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
