# Generated by Django 4.2 on 2023-06-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rohan', '0003_remove_contactus_phonenumber_contactus_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='phone',
            new_name='phonenumber',
        ),
    ]
