# Generated by Django 4.2 on 2023-06-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rohan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phonenumber',
            field=models.BigIntegerField(),
        ),
    ]
